### PR TITLE
targeting cake version 0.25.0

### PR DESCRIPTION
**Pull request by ubbeK**
issue https://github.com/cake-contrib/Cake.CMake/issues/12

  cc @patriksvensson

### CODE REVIEW

**Comment by ubbeK** [comment]
No feedback regarding this? @patriksvensson

**Comment by patriksvensson** [comment]
@ubbeK I’ve been on vacation and now I’m home with my daughter until she starts her new pre-school. Will get back to this as soon as I can and have some free time.

**Comment by jkoritzinsky** [comment]
Any update on this? We were hoping to hook CMake into our Cake build and we'd need this PR merged in to get that working.

**Comment by darlov** [comment]
Package was released with Cake.Core 0.34.1.

**Pull request closed without merging**
